NuGet.Docs/_Layout.cshtml

The edit link on an document page was still to the `site` folder instead of `NuGet.Docs`

Fixed edit link

---

NuGet.Docs/Contribute/Ecosystem.md

during the rename from .markdown to .md the page wasn't updated. Fixed now.

Fixed the page own URL

---

NuGet.Docs/Create/Nuspec-Reference.md

The links are case sensitive so currently the development-only dependency link just points you to the 2.7 release notes instead of the specific section associated with the change.  This updates to use the correctly cased link.

Update link to developmentDependency change notes.

---

NuGet.Docs/Consume/NuGet-Config-Settings.md

The word 'currently' was used twice in the sentence. This removes the second use.

Remove redundant word in config settings doc

---

NuGet.Docs/css/nuget.docs.css

This changes makes sure that image files are not overflowing the viewport when using a small screen device, but adjusted its width with the parent container

Make images reponsive

---

NuGet.Docs/Consume/Package-Restore.md

There's a lot of confusion of what the 'state' of the config file should look like under each version of Automatic Package Restore.  Based on the other documents, it's inferred what the state *should* be, but never outright explicitly stated.  This addition makes it clear which version produces which outcome.

Spelling out each state of Automatic Package Restore

---

NuGet.Docs/Create/Packages-in-Visual-Studio-Templates.md

Explains more clearly that the project or item template authored into the VSIX should itself not include the artifacts that NuGet would add to a project. This seems non-obvious to folks since when they're reading these docs, they already have a working project template and they want to NuGet-tize it. So the first step is to actually _remove_ all the references from their template that they need, since NuGet will be responsible to add them right back. 
This commit adds the necessary explanatory text.

Explain that vs templates should omit nuget refs

---

NuGet.Docs/Create/Packages-in-Visual-Studio-Templates.md

The doc only included a sample of how to modify the extension.vsixmanifest file based on a very old schema. The newer schema required guesswork to adapt. I've added the actual sample so folks will find it easier.
I also clarified a bit of the surrounding wording.

Add 2.0 schema example to NuGet custom wizard doc

---

NuGet.Docs/Consume/NuGet-Config-Settings.md

In Version 2.7, Nuget offered a 'new' way of doing package restore that doesn't require what Pre-2.7 requires.  This is evident after a long read of the changes, but not evident here; which could cause confusion and unexpected behavior.  This edit simply clarifies what version this setting works for.

Clarify which version this Package Restore setting is for

---

NuGet.Docs/Consume/NuGet-Config-File.md

Two small fixes to make the documentation easier to read...

Fix "Credentials for package source" section of "NuGet Config File" page

---

NuGet.Docs/Create/Creating-and-Publishing-a-Package.md

Link incorrectly points to /Create/Creating-Packages-With-Configuration-File-and-Source-Code-Transformations.
Changed to /Create/Configuration-File-and-Source-Code-Transformations

Fix broken link.

---

NuGet.Docs/Contribute/Setting-up-the-NuGet-Development-Environment.md

The old URL was still pointing at CodePlex

Fix git clone URL and branch for development

---

NuGet.Docs/Contribute/Project-Contribution-Guidelines.md

cc @csharpfritz @yishaigalatzer 
Very similar to the aspnet/home contribution guidelines.
References updated CLA for .NET Foundation.
Related to #336

updated contribution guidelines + added CLA for .NET Foundation

---

NuGet.Docs/Create/Default.cshtml

Fixed a minor typo under the heading "Symbol, Localized and Transform Packages". The descriptive sentence had
"... dependenvy ..."
It should be
"... dependency ..."

Minor Typo

---

NuGet.Docs/Consume/Package-Restore/Team-Build.md

Correct usages of "on-premise" to be "on-premises".  Use hyphenated "on-premises" consistently.

Team-Build.md: "on-premises" not "on-premise"

---

NuGet.Docs/Consume/Command-Line-Reference.md

The instructions available now point to TeamCity build server, where, currently at least, Guests do not have access to any projects.
I found that the NuGet.ServerExtensions.dll is available on the CodePlex site for Nuget2. Also it appears that the dll is build against signed NuGet.exe (discussed in #559), so it is also needed to download the NuGet-Signed.exe.

Fixed how-to enable nuget.exe mirror command

---

NuGet.Docs/Consume/NuGet-Config-File.md

I think there is a small typo in "NuGet config extensibility point" section, in paragraph "Starting with NuGet 2.6...".
There is: c:\a\b\c.nuget\nuget.config
While, I believe, it should be: c:\a\b\c\\.nuget\nuget.config
Similarly to the list in the first paragraph.

Incorrect(?) path to nuget.config file: c:\a\b\c.nuget -> c:\a\b\c\.nuget

---

NuGet.Docs/Create/Analyzers-Conventions.md

This adds the details about analyzer conventions in nuget packages

Adding documentation on conventions for Analyzers.

---

NuGet.Docs/Consume/Command-Line-Reference.md
NuGet.Docs/Create/Creating-and-Publishing-a-Package.md

- Add documentation on -MSBuildVersion
- Make it clear that token replacement is not supported when pack from a nuspec file.
@yishaigalatzer @csharpfritz @emgarten @MeniZalzman @deepakaravindr

Documentation updates

---

NuGet.Docs/Create/Creating-and-Publishing-a-Symbol-Package.md

As we've set up our new production symbol repository, I am proposing a change to the docs to reflect that. I will submit an issue to also update the hardcoded nuget.exe push URL.
Please note that our docs are not yet updated on the SymbolSource.org site, but we'd like all users to benefit from the faster and more stable engine as soon as possible.

Updated URLs to use the new SymbolSource service

---

NuGet.Docs/Contribute/Contributing-to-NuGet.md

On the [page](https://docs.nuget.org/contribute/contributing-to-nuget) it currently points to
https://docs.nuget.org/contribute/Project-Guidelines which 404s
rather than
https://docs.nuget.org/Contribute/Project-Contribution-Guidelines

Fix broken link

---

NuGet.Docs/Consume/Package-Restore.md

Just a little typo, "If you are on TFS 2012 or newer, or using VSO, you'll need to add a .tfignore file tho explicitly ...", the "tho" was changed to "to"

Fix typo in /consume/package-restore

---

NuGet.Docs/Create/Nuspec-Reference.md

32x32 is tiny and outdated. The NuGet Gallery can handle larger icons.

Update iconUrl doc to prescribe 64x64 icon

---

NuGet.Docs/Create/Versioning.md

Semver 2.0.0 is not yet supported by nuget, this remedies some confusion that may arise.

Point to Correct Version of SemVer

---

NuGet.Docs/Create/Versioning.md

According to this blog post (http://www.jeffreyfritz.com/2015/12/the-case-of-the-old-nuget-dependency-installation/) when a version is not specified the lowest version is used.  
"Starting with v2.8, NuGet is more conservative by default and will install the lowest version of packages that the package author depends on"
The docs state that the latest version is used which is not correct.

[Docs] Versioning - changed "empty" version to indicate the lowest

---

NuGet.Docs/Consume/ProjectJson-Format.md

But although this is a misspelling, it's only correct to "fix" it if in fact the product itself doesn't share the misspelling. Does anyone know?

Fix mispelling in project.json supports field

---

README.markdown

Updating the README to point to NuGet/Home, where @csharpfritz directed me for docs issues.

Updating README to include right place for issues

---

NuGet.Docs/Create/Nuspec-Reference.md

Document special casing of 'fs' as content language for F#, and make it clear that codeLanguage can match the lowercase equivalent of the ProjectLanguage property of a given project.
Fixes [#1825](https://github.com/NuGet/Home/issues/1825).

Add 'fs' as content language, and document ProjectLanguage matching

---

NuGet.Docs/Consume/NuGet-Config-File.md

Adding documentation for NuGet/NuGet.Client#171; the implementation of NuGet/Home#1852

Issue 1852 eval env variables in config values

---

NuGet.Docs/Consume/Command-Line-Reference.md

From nuget.exe printout:
WARNING: Option 'NoPrompt' has been deprecated. Use 'NonInteractive' instead.

Remove deprecated NoPrompt flag from delete documentation

---

NuGet.Docs/Consume/Command-Line-Reference.md

Those parameters are unused in code, and having them documented is confusing
@harikm86 , @yishaigalatzer

Remove unused parameters from nuget.exe init + nuget.exe add

---

NuGet.Docs/Create/Package-Types.md

This addresses https://github.com/NuGet/Home/issues/3026.
This is user-facing documentation about package types. This document is intended to be more approachable than the original [Package Type design document](https://github.com/NuGet/Home/wiki/Package-Type).
Note that the other similar PR (https://github.com/NuGet/NuGetDocs/pull/492) is for @harikmenon's `proto` branch. This PR is hanging off of `master`.

Add package type documentation

---

NuGet.Docs/ndocs/Guides/Install-NuGet.md

Updated right tool matrix:
- Split first row to search package and install package. There's no command to download a package without installing it.
- In NuGet in .NET CLI it states the only command available is dotnet restore. So the matrix should be aligned with that.
Added choco command line to install NuGet.
Changed casing in section titles

Changes in Install NuGet Guide

---

NuGet.Docs/ndocs/Schema/nuspec.md

- Talked to @karann-msft, code should have one `\t` at the beginning of each line. Did that.
- Remove old usages of backtick for code.
- Added a line about package types.
- Little cleanups.

Polish off .nuspec documentation

---

NuGet.Docs/ndocs/Tools/NuGet-CLI-Reference.md

This adds descriptions of what the install and update commands do and do not do with projects, there has been a lot of issues filed around this.
I've removed the user nuget.config paths from descriptions where it does not apply. It looks like these docs were not updated after the hierarchical nuget.config feature was added, there are many places that nuget.config can come from.
Other misc clean up.
//cc @harikmenon

Update NuGet CLI doc

---

NuGet.Docs/ndocs/Consume-Packages/nuget-config-File-Overview.md

Adding versions to the -configfile switch docs to have better clarity about the behavior for different versions of nuget.exe
Addresses- https://github.com/NuGet/Home/issues/3208 https://github.com/NuGet/Home/issues/3221
cc : @harikmenon  @karann-msft

Adding versions to -configfile docs to clarify behavior

---

NuGet.Docs/ndocs/Guides/Create-NET-Standard-Packages.md

"NuGet spec" command generated a .nuspec with the name of the project, not Package.nuspec

Fixed nuspec default name

---

NuGet.Docs/ndocs/Create-Packages/Supporting-Multiple-Target-Frameworks.md

The text explains it correctly:
"the highest version that is less than or equal to the project's target framework"
Although the note below the table states that 4.6.1 would be installed when a 4.6 is targeted.

Backwards compatibility error

---

NuGet.Docs/ndocs/Schema/nuget.config-file.md

The hyperlink is being built as http://docs.nuget.org/ndocs/schema/ndocs/consume-packages/configuring-nuget-behavior
The node "ndocs" after "schema" should not be there.

remove ndoc from hyperlink

---

NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md

I believe that the fileconflictactions option in the update command should not be pluralized and should match the option for the install command which is just fileconflictaction.

Fix typo in update command option

---

NuGet.Docs/ndocs/Create-Packages/Publish-a-package.md

It appears that the source argument is now required. See https://github.com/NuGet/Home/issues/2504 and https://github.com/NuGet/NuGetGallery/pull/3011 for more details.

Add mandatory source argument

---

NuGet.Docs/ndocs/Policies/Ecosystem.md

As advised by a NuGet team member, I added a link in the `Non-Microsoft projects` section, to a minimal implementation of a NuGet server, self-hostable on any OS thanks to .NET Core.

Added a link to the Non-Microsoft projects section

---

NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md

During hours of my developer life debugging odd NuGet command-line client "randomly" different behaviors on build systems vs. locally I've found when going thru NuGet client source that there's several environment variable which affects the default behaviors of the NuGet CLI.
I've found the documentation for these environment variables somewhat lacking and therefore propose this PR which documents several of the environment variables available as an addition at the bottom of the NuGet CLI reference documentation.

Adds command-line environment variable documentation

---

NuGet.Docs/ndocs/Visual-Studio-Extensibility/Visual-Studio-Templates.md

The formatting here was rendering incorrectly. It looks like just the extra line break was messing things up.
https://docs.nuget.org/ndocs/visual-studio-extensibility/visual-studio-templates

Fix broken formatting

---

NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md

Added a note that a package sources' password must be stored under the same user context as it is decrypted.
I wasn't able to find this information anywhere in the docs.

Added note to sources section

---

NuGet.Docs/ndocs/Schema/nuget.config-file.md

The document says we can use ``HTTP_PROXY`` and ``NO_PROXY`` environment variables for proxy configuration. However, on the Linux, capitalized ``HTTP_PROXY`` and ``NO_PROXY`` are not working because NuGet.Client gets environmental variable as the key is small letter ``http_proxy`` and ``no_proxy``.
https://github.com/NuGet/NuGet.Client/blob/4cccb13833ad29d6a0bcff055460d964f1b49cfe/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L114-L141
https://github.com/NuGet/NuGet.Client/blob/4cccb13833ad29d6a0bcff055460d964f1b49cfe/src/NuGet.Core/NuGet.Configuration/Utility/ConfigurationContants.cs#L34-L40
For the Windows users, this can work because Windows environmental variable key is case insensitive,  but Linux is case sentive. Now .NET Core and Nuget.Core is cross platform, so could you …

Uncapitalize http_proxy and no_proxy environment for Linux users.

---

NuGet.Docs/ndocs/Create-Packages/Creating-a-Package.md
NuGet.Docs/ndocs/Create-Packages/Dependency-Versions.md

Reporting by user message to feedback (at) nuget (dot) org.
1. The `2016/06` schema version was reverted before releasing. The latest schema is `2013/05`.
1. The package type name attribute is `name` not `type`.
/cc @karann-msft

Remove invalid schema version from .nuspec examples and fix package type

---

NuGet.Docs/Web.config

This add the "Strict-Transport-Security" header to responses from this app, enabling browsers that support HSTS (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) to enforce it.
@karann-msft

Enable HSTS header on responses

---

NuGet.Docs/ndocs/Create-Packages/Dependency-Versions.md

Make Depenency-Versions.md more readible by reformatting the table. Using markdown |--| table syntax instead of <table>. This also fixes the table formatting error on https://docs.nuget.org/ndocs/create-packages/dependency-versions.

Improve Depenency-Versions.md readability

---

NuGet.Docs/ndocs/Consume-Packages/Reinstalling-and-Updating-Packages.md

Match the code sample and the intention of the example => [1,2) rather than [1,2].

Fix typo in "Constraining upgrade versions"
