NuGet.Docs/Consume/Package-Manager-Console.md
Added an [here] before the file reference to make it a clickable link
=> Reference to another file was not clickable.

NuGet.Docs/Contribute/Ecosystem.md
Added more detailed description and more links to additional information
=> Updated information on Artifactory

NuGet.Docs/Consume/Package-Restore/Team-Build.md
The prose indicates this change is for TFS 2012 and earlier; but you have to read through a paragraph to see that.  This edit just makes it readily apparent when visiting the page.
=> Spell out what version this document is for clearly

NuGet.Docs/Create/Nuspec-Reference.md
Reference docs for target property of files element could be clearer
=> Fixes "Reference docs for target property" #25

NuGet.Docs/Consume/Package-Manager-Console-PowerShell-Reference.md
updated the document for new commands and switches
=> Update Package Manager Console Reference after changes in NuGet 3.0 Beta

NuGet.Docs/Contribute/Setting-up-the-NuGet-Development-Environment.md
Updated the documentation to use the latest instructions about how to build NuGet.VisualStudioExtension
=> Fixed https://github.com/NuGet/Home/issues/459

NuGet.Docs/Consume/Installing-NuGet.md, NuGet.Docs/Consume/NuGet-FAQ.md, NuGet.Docs/Contribute/Ecosystem.md, NuGet.Docs/Contribute/NuGet-Client-Test-Plan.md, NuGet.Docs/Contribute/NuGet-Gallery-Test-Plan.md
Remove references to WebMatrix
=> Remove references to WebMatrix

NuGet.Docs/Default.cshtml, NuGet.Docs/Release-Notes/NuGet-3.0-RC2.md, NuGet.Docs/Release-Notes/NuGet-3.0.0.md
Updated with 3.0 release notes to be published after Visual Studio 2015 is released on July 20
=> 3.0 release notes

NuGet.Docs/Consume/Installing-NuGet.md
=> Updated section on installing CI build of VSIX

NuGet.Docs/Create/Default.cshtml, NuGet.Docs/Create/Project-System-Support.md
Please do *not* merge this before NuGet/NuGet.VisualStudioExtension#51 is merged.
=> Doc how to add NuGet support to project systems

NuGet.Docs/Consume/NuGet-Config-Defaults.md
This makes the subject more understandable.
=> Add link to NuGet-Config-File doku

NuGet.Docs/Consume/NuGet-Config-Settings.md, NuGet.Docs/Create/uwp-create.md
Added information about dependencyVersion configuration to nuget.config docs.  Addresses part of NuGet/Home#1195
=> Added dependencyVersion to nuget.config

NuGet.Docs/Create/Default.cshtml
Missing the root "/" from some links, though probably all paths should be made relative!
=> Fixed incorrect paths used in links

NuGet.Docs/Create/Creating-and-Publishing-a-Package.md
=> Added information about pack against csproj file

NuGet.Docs/Create/Creating-Localized-Packages.md
doc update for https://github.com/NuGet/Home/issues/1482
=> doc update for https://github.com/NuGet/Home/issues/1482

NuGet.Docs/Create/Creating-and-Publishing-a-Symbol-Package.md
Reverts NuGet/NuGetDocs#386 as per https://github.com/NuGet/NuGet2/pull/20#issuecomment-149907930
=> Revert "Updated URLs to use the new SymbolSource service"

NuGet.Docs/Consume/Command-Line-Reference.md
Documentation for nuget.exe add and nuget.exe init commands
@yishaigalatzer @emgarten @MeniZalzman @zhili1208
=> Documentation for nuget.exe add and nuget.exe init commands

NuGet.Docs/Contribute/Ecosystem.md
When it goes into public preview, the wording can be tweaked slightly.
=> Add VSO package management

NuGet.Docs/Contribute/Setting-up-the-NuGet-Development-Environment.md
This is to fix the broken link to the visual studio 2015 SDK.
=> Fixing broken link to the visual studio 2015 SDK

NuGet.Docs/Consume/Credential-Providers.md, NuGet.Docs/Consume/Default.cshtml
Added a new article about Credential Providers for NuGet 3.3.
=> Adding Credential Provider docs.

NuGet.Docs/Create/Creating-and-Publishing-a-Package.md
=> Added steps to create nupkg as part of build

NuGet.Docs/Consume/Credential-Providers.md
Added instructions to create a credential provider.
=> Updating Credential Provider docs

NuGet.Docs/Create/Versioning.md
I fixed a typo with the word specify :)
=> fixed typo in my last PR

NuGet.Docs/Create/Creating-and-Publishing-a-Package.md
=> Fix a small typo

NuGet.Docs/Consume/Package-Manager-Ui.md
=> Fix minor typo

NuGet.Docs/Create/Hosting-Your-Own-NuGet-Feeds.md
Addresses instructions to maintain folder repository with CLI as outlined in NuGet/Home#1807
=> Added instructions to create and manage new folder repositories

NuGet.Docs/Create/Default.cshtml, NuGet.Docs/Create/TargetFrameworks.md
Target Frameworks supported by NuGet official clients defined and documented in response to NuGet/Home#358
=> TargetFrameworks article

NuGet.Docs/Contribute/Setting-up-the-NuGet-Development-Environment.md
Updated getting started page with VS2015.1 and ASP.NET 5 requirements.
https://github.com/NuGet/Home/issues/1790.
=> Updated minimal requirements for NuGet development.

NuGet.Docs/Create/Creating-and-Publishing-a-Symbol-Package.md
=> Updated URLs to use the new SymbolSource service

NuGet.Docs/Consume/NuGet-Config-Settings.md
Fixed merge and squashed commits from PR #379
=> convert from html table layout to markdown paragraph layout

NuGet.Docs/Consume/NuGet-FAQ.md
fixed the link to Rob Reynold's blog post
=> Fix link faq

NuGet.Docs/Create/Versioning.md
Supports changes discussed in NuGet/Home#2298
=> Added normalized version number section

NuGet.Docs/Release-Notes/NuGet-3.4.2.md
=> 3.4.2 release notes

NuGet.Docs/Create/Creating-and-Publishing-a-Symbol-Package.md
=> Updated symbols info

NuGet.Docs/Create/Creating-and-Publishing-a-Symbol-Package.md
=> Some more nits

NuGet.Docs/Consume/Command-Line-Reference.md, NuGet.Docs/Create/Creating-and-Publishing-a-Symbol-Package.md
Update to delete documentation
=> Update to delete documentation

NuGet.Docs/Consume/NuGet-Config-Settings.md
@yishaigalatzer , @harikm86 
Fixing an issue created here: https://github.com/NuGet/NuGetGallery/issues/3001
=> Relative repository path is relative to NuGet.config, not solution

NuGet.Docs/Consume/Command-Line-Reference.md
Fix https://github.com/NuGet/Home/issues/3025
=> Updated doc to add -Version option for update command.

NuGet.Docs/Release-Notes/NuGet-2.12-RC.md, NuGet.Docs/Release-Notes/_metadata
=> Harikm86 relnotes 2.12 rc

NuGet.Docs/ndocs/Create-Packages/Source-File-Transformations.md
the link to Transform Web.Config using .transform Files was not found. I guess the correct link should be Config-File-Transformations.md
Fixing path in pp.files.png
=> fix broken link and broken img

NuGet.Docs/_LayoutHome.cshtml, NuGet.Docs/ndocs/Create-Packages/Supporting-Mulitple-Target-Frameworks.md
=> fix broken link

NuGet.Docs/ndocs/Tools/NuGet-CLI-Reference.md
I finished up to Update, about to start restore, but I'm going to switch to a local copy.
=> In progress of CLI Reference

NuGet.Docs/ndocs/Create-Packages/SemVer-Support.md
Editing the SemVer doc to make it more readable and implement styling changes.
=> First pass editing SemVer doc.

NuGet.Docs/ndocs/Quickstart/Create-a-Package.md
Emphasize this tutorial is built for VS2015.
=> Minor fixes to Create-a-Package

NuGet.Docs/Release-Notes/3.5-RC.md, NuGet.Docs/Release-Notes/_metadata
=> Release Notes for 3.5 RC

NuGet.Docs/ndocs/Create-Packages/Supporting-Multiple-Target-Frameworks.md
Removed extra <br> and fixed some sentences.
=> Removed extra <br>

NuGet.Docs/_Layout.cshtml
Added a new TAB for docs preview
=> Updated TOC

NuGet.Docs/Create/Versioning.md
Thought an extra example would be helpful in the documentation
=> Update Versioning.md to add greater than or equal example

NuGet.Docs/ndocs/Quickstart/Create-and-Publish-a-Package.md, NuGet.Docs/ndocs/Quickstart/Use-a-Package.md
Added <code> elements around code blocks that needed them.
=> Fix typos and code formatting

NuGet.Docs/Consume/NuGet-Config-Defaults.md
Updating docs in response to https://github.com/NuGet/Home/issues/3426
@yishaigalatzer looks good?
CC: @harikmenon
=> Changes in the Default Package Sources behavior

NuGet.Docs/Create/Nuspec-Reference.md
https://github.com/NuGet/Home/issues/3360
=> Specifying an empty reference element is a no-op

NuGet.Docs/Contribute/Ecosystem.md
It's development lives on GitHub now and it has it's own website
=> Updated Boxstarter links

NuGet.Docs/Consume/Command-Line-Reference.md
This can go in if the change for https://github.com/NuGet/Home/issues/2348 is accepted
=> Add doc for -SymbolsSource and -SymbolsApiKey for 3.5

NuGet.Docs/ndocs/Schema/nuspec.md
Fixed link to nuspec version ranges
=> Fixed href

NuGet.Docs/NuGet.Docs.csproj, NuGet.Docs/docs/Reference/Support-for-native-projects.cshtml, NuGet.Docs/ndocs/Consume-Packages/Support-for-Native-Projects.cshtml, NuGet.Docs/ndocs/Create-Packages/Native-Packages.md
Includes adding a couple of redirects
=> Correcting Native Package topic links

NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md
=> Mention the new -DirectDownload switch for nuget.exe install and update

NuGet.Docs/ndocs/API/Credential-Providers.md
Documentation for the fix for NuGet/Home#3439
=> Add "Verbosity" parameter to Credential Provider documentation.

NuGet.Docs/ndocs/Consume-Packages/Package-Restore.md
=> Fix link and item new line.

NuGet.Docs/ndocs/Create-Packages/Symbol-Packages.md
NuGet pack code sample is properly formatted.
=> Fix nuget pack code sample

NuGet.Docs/create/Enforced-Package-Conventions.cshtml
Fixed type in target filename.
=> Fix redirect - use correct page name

NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md
Fixed a few typos,  inconsistent casing and incorrect encoding of `<` and `>`.
=> Fixed typos & inconsistencies

NuGet.Docs/ndocs/Create-Packages/Supporting-Multiple-Target-Frameworks.md
was dir `create-package` but should be `create-packages`
=> fix 404 link to incorrect directory in slug

NuGet.Docs/ndocs/Consume-Packages/Configuring-NuGet-Behavior.md
https://github.com/NuGet/NuGetGallery/issues/3338
=> Fix for https://github.com/NuGet/NuGetGallery/issues/3338

NuGet.Docs/ndocs/API/NuGet-Credential-Providers-for-Visual-Studio.md
=> Added a plug-in credential provider to the list

NuGet.Docs/ndocs/Create-Packages/Dependency-Versions.md
There are a couple usages of it below in the examples, it would help to describe it in the table.
=> Add mixed inclusive/exclusive notation to table

NuGet.Docs/ndocs/Consume-Packages/Overview-and-Workflow.md, NuGet.Docs/ndocs/Consume-Packages/Packages-and-Source-Control.md, NuGet.Docs/ndocs/Create-Packages/Creating-a-Package.md, NuGet.Docs/ndocs/Create-Packages/Overview-and-Workflow.md, NuGet.Docs/ndocs/Release-Notes/NuGet-3.2.1.md, NuGet.Docs/ndocs/Schema/nuget.config-file.md, NuGet.Docs/ndocs/Tools/NuGet.exe-CLI-Reference.md
Including a few other miscellaneous corrections as well.
=> Addressing issues 2326, 2823, 3745, and 3511

NuGet.Docs/ndocs/Create-Packages/Creating-a-Package.md
also removed a superfluous period
=> random extra letter was displaying over the table

NuGet.Docs/ndocs/Create-Packages/Dependency-Versions.md
Make Depenency-Versions.md more readible by fixing some formatting errors in the Normalized version numbers section.
=> Improve Depenency-Versions.md readability

NuGet.Docs/ndocs/Create-Packages/Dependency-Versions.md
=> Revert "Improve Depenency-Versions.md readability"

NuGet.Docs/ndocs/Schema/nuspec.md
Wrong tag round `<files>` here.
=> Minor typo
